In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('train.csv')

In [9]:
for i in df.columns:
    print(df[i].value_counts())

1094    2
1093    2
1091    2
1095    2
1092    2
       ..
926     1
925     1
923     1
922     1
0       1
Name: Feature 1 (Discrete), Length: 989, dtype: int64
3     301
0     291
12     84
7      79
4      42
15     37
8      27
20     16
5      14
16     14
14     10
10      9
11      9
2       8
38      7
31      6
35      4
23      4
21      3
25      3
26      3
24      2
13      2
6       2
33      2
22      1
34      1
1       1
42      1
40      1
39      1
37      1
32      1
9       1
44      1
30      1
28      1
27      1
19      1
46      1
Name: Feature 2 (Discrete), dtype: int64
40     52
179    43
92     40
145    34
245    32
       ..
224     1
221     1
218     1
217     1
0       1
Name: Feature 3 (Discrete), Length: 303, dtype: int64
2     406
14    137
5      85
1      45
16     43
     ...
54      1
25      1
53      1
52      1
79      1
Name: Feature 4 (Discrete), Length: 65, dtype: int64
1     398
3     199
2     167
0      62
5      53
11     52
8      21
7      19
4      13
6       4
10      2
9       2
14      1
13      1
Name: Feature 5 (Discrete), dtype: int64
0    543
1    352
2     72
3     26
4      1
Name: Feature 6 (Discrete), dtype: int64
1     733
4     111
2      33
3      28
6      25
9      15
0      14
8       8
10      7
19      4
13      3
18      2
5       2
14      2
16      2
12      1
11      1
7       1
15      1
17      1
Name: Feature 7 (Discrete), dtype: int64
1    364
0    259
3    229
4     98
2     19
7     11
5      9
6      5
Name: Feature 8 (Discrete), dtype: int64
 0.001      147
 0.004      144
 0.002      132
 0.005      114
 0.003      111
           ...
 307.003      1
-114.957      1
-114.899      1
 25.505       1
-116.795      1
Name: Feature 9, Length: 332, dtype: int64
776.4      10
35778.3     9
776.1       8
35775.1     7
35776.5     7
           ..
442.5       1
607.2       1
20446.2     1
19114.3     1
501.5       1
Name: Feature 10, Length: 683, dtype: int64
779.2      8
779.3      8
779.4      7
35795.2    6
1414.1     6
          ..
491.5      1
482.5      1
879.2      1
1412.1     1
492.5      1
Name: Feature 11, Length: 686, dtype: int64
0.000064    12
0.000012     8
0.000210     8
0.000071     8
0.000210     7
            ..
0.001200     1
0.000208     1
0.000181     1
0.021500     1
0.000522     1
Name: Feature 12, Length: 703, dtype: int64
0.053     13
86.403    12
0.023     11
0.011     10
86.404    10
          ..
98.562     1
82.453     1
97.871     1
64.811     1
4.922      1
Name: Feature 13, Length: 522, dtype: int64
1436.104    26
1436.105    22
1436.103    22
1436.101    20
1436.102    19
            ..
718.021      1
98.465       1
115.864      1
97.505       1
94.625       1
Name: Feature 14, Length: 607, dtype: int64
4.1       12
689.1     12
4.2       11
689.5     10
700.3      9
          ..
4900.5     1
3700.2     1
1500.4     1
2120.3     1
14.5       1
Name: Feature 15, Length: 601, dtype: int64
556.3     11
556.4     10
556.2      8
556.1      7
556.5      7
          ..
2000.2     1
1530.4     1
2150.3     1
1100.5     1
1540.3     1
Name: Feature 16, Length: 217, dtype: int64
1400.004    11
1400.001    11
1400.002    11
1500.002     9
1500.003     8
            ..
80.002       1
7000.001     1
1485.003     1
220.001      1
3800.001     1
Name: Feature 17, Length: 251, dtype: int64
15.01       43
15.02       39
15.03       38
15.05       35
15.04       32
            ..
14.05        1
44022.04     1
20.05        1
14.02        1
44022.05     1
Name: Feature 18, Length: 105, dtype: int64
1      71
2      59
30     50
152    43
12     43
       ..
185     1
183     1
182     1
181     1
0       1
Name: Feature 19 (Discrete), Length: 259, dtype: int64
1     475
12    128
6      81
2      63
15     36
18     24
14     23
7      16
3      13
11     12
8      10
16      9
32      8
4       7
55      7
23      6
34      6
19      5
10      5
24      5
26      4
29      4
39      4
0       3
33      3
40      3
57      2
25      2
44      2
49      2
22      2
50      2
51      2
56      2
5       1
13      1
9       1
58      1
17      1
30      1
31      1
35      1
36      1
37      1
38      1
41      1
42      1
45      1
46      1
47      1
53      1
28      1
Name: Feature 20 (Discrete), dtype: int64
3     173
1     160
0     158
4      92
10     60
7      59
2      47
6      47
5      46
11     40
12     26
18     25
15     21
13     16
9       9
23      4
14      3
20      3
22      1
8       1
16      1
17      1
19      1
Name: Feature 21 (Discrete), dtype: int64
10     66
11     54
20     46
47     42
19     41
       ..
91      1
97      1
101     1
104     1
72      1
Name: Feature 22 (Discrete), Length: 137, dtype: int64
1417    1
469     1
488     1
487     1
485     1
       ..
934     1
933     1
932     1
929     1
0       1
Name: Feature 23 (Discrete), Length: 994, dtype: int64
40934.3    1
28915.2    1
40482.1    1
37791.1    1
36508.1    1
          ..
41181.5    1
37606.1    1
25258.5    1
26356.1    1
38736.3    1
Name: Feature 24, Length: 993, dtype: int64
1     488
0     249
2     109
6      70
5      41
8       7
7       5
14      5
15      4
13      3
4       3
3       3
9       2
11      1
10      1
16      1
12      1
17      1
Name: Target Variable (Discrete), dtype: int64

In [28]:
df.isna().sum()

Feature 1 (Discrete)            0
Feature 2 (Discrete)            0
Feature 3 (Discrete)            0
Feature 4 (Discrete)            0
Feature 5 (Discrete)            0
Feature 6 (Discrete)            0
Feature 7 (Discrete)            0
Feature 8 (Discrete)            0
Feature 9                      14
Feature 10                      1
Feature 11                      1
Feature 12                      1
Feature 13                      1
Feature 14                      1
Feature 15                     72
Feature 16                    669
Feature 17                    546
Feature 18                    330
Feature 19 (Discrete)           0
Feature 20 (Discrete)           0
Feature 21 (Discrete)           0
Feature 22 (Discrete)           0
Feature 23 (Discrete)           0
Feature 24                      1
Target Variable (Discrete)      0
dtype: int64

In [11]:
df_test=pd.read_csv('test.csv')

In [13]:
df.columns

Index(['Feature 1 (Discrete)', 'Feature 2 (Discrete)', 'Feature 3 (Discrete)',
       'Feature 4 (Discrete)', 'Feature 5 (Discrete)', 'Feature 6 (Discrete)',
       'Feature 7 (Discrete)', 'Feature 8 (Discrete)', 'Feature 9',
       'Feature 10', 'Feature 11', 'Feature 12', 'Feature 13', 'Feature 14',
       'Feature 15', 'Feature 16', 'Feature 17', 'Feature 18',
       'Feature 19 (Discrete)', 'Feature 20 (Discrete)',
       'Feature 21 (Discrete)', 'Feature 22 (Discrete)',
       'Feature 23 (Discrete)', 'Feature 24', 'Target Variable (Discrete)'],
      dtype='object')

In [33]:
df.drop(['Feature 16', 'Feature 17'], axis=1, inplace=True) # Largw number of missing values

In [35]:
df_test.drop(['Feature 16', 'Feature 17'], axis=1, inplace=True)

In [36]:
df_test.columns

Index(['Feature 1 (Discrete)', 'Feature 2 (Discrete)', 'Feature 3 (Discrete)',
       'Feature 4 (Discrete)', 'Feature 5 (Discrete)', 'Feature 6 (Discrete)',
       'Feature 7 (Discrete)', 'Feature 8 (Discrete)', 'Feature 9',
       'Feature 10', 'Feature 11', 'Feature 12', 'Feature 13', 'Feature 14',
       'Feature 15', 'Feature 18', 'Feature 19 (Discrete)',
       'Feature 20 (Discrete)', 'Feature 21 (Discrete)',
       'Feature 22 (Discrete)', 'Feature 23 (Discrete)', 'Feature 24'],
      dtype='object')

In [37]:
df.head()

,Feature 1 (Discrete),Feature 2 (Discrete),Feature 3 (Discrete),Feature 4 (Discrete),Feature 5 (Discrete),Feature 6 (Discrete),Feature 7 (Discrete),Feature 8 (Discrete),Feature 9,Feature 10,...,Feature 14,Feature 15,Feature 18,Feature 19 (Discrete),Feature 20 (Discrete),Feature 21 (Discrete),Feature 22 (Discrete),Feature 23 (Discrete),Feature 24,Target Variable (Discrete)
0,1404,12,64,14,3,1,1,1,110.502,35775.2,...,1436.052,5000.5,15.04,104,12,2,32,1409,37677.1,1
1,909,0,235,32,1,1,1,1,-40.448,35779.4,...,1436.111,3720.5,12.03,20,1,0,13,909,25239.1,1
2,654,3,175,2,1,1,1,1,-27.445,35770.4,...,1436.103,4685.4,13.01,1,1,0,13,654,27683.5,1
3,1372,12,382,14,2,0,1,0,0.001,509.2,...,94.844,NaN,NaN,313,12,10,54,1377,39363.2,0
4,786,3,199,2,1,0,1,0,0.001,612.1,...,97.823,4.1,NaN,171,1,5,11,786,40044.4,2

In [38]:
df.isna().sum()

Feature 1 (Discrete)            0
Feature 2 (Discrete)            0
Feature 3 (Discrete)            0
Feature 4 (Discrete)            0
Feature 5 (Discrete)            0
Feature 6 (Discrete)            0
Feature 7 (Discrete)            0
Feature 8 (Discrete)            0
Feature 9                      14
Feature 10                      1
Feature 11                      1
Feature 12                      1
Feature 13                      1
Feature 14                      1
Feature 15                     72
Feature 18                    330
Feature 19 (Discrete)           0
Feature 20 (Discrete)           0
Feature 21 (Discrete)           0
Feature 22 (Discrete)           0
Feature 23 (Discrete)           0
Feature 24                      1
Target Variable (Discrete)      0
dtype: int64

In [39]:
df

,Feature 1 (Discrete),Feature 2 (Discrete),Feature 3 (Discrete),Feature 4 (Discrete),Feature 5 (Discrete),Feature 6 (Discrete),Feature 7 (Discrete),Feature 8 (Discrete),Feature 9,Feature 10,...,Feature 14,Feature 15,Feature 18,Feature 19 (Discrete),Feature 20 (Discrete),Feature 21 (Discrete),Feature 22 (Discrete),Feature 23 (Discrete),Feature 24,Target Variable (Discrete)
0,1404,12,64,14,3,1,1,1,110.502,35775.2,...,1436.052,5000.5,15.04,104,12,2,32,1409,37677.1,1
1,909,0,235,32,1,1,1,1,-40.448,35779.4,...,1436.111,3720.5,12.03,20,1,0,13,909,25239.1,1
2,654,3,175,2,1,1,1,1,-27.445,35770.4,...,1436.103,4685.4,13.01,1,1,0,13,654,27683.5,1
3,1372,12,382,14,2,0,1,0,0.001,509.2,...,94.844,NaN,NaN,313,12,10,54,1377,39363.2,0
4,786,3,199,2,1,0,1,0,0.001,612.1,...,97.823,4.1,NaN,171,1,5,11,786,40044.4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
989,1388,0,382,14,2,0,1,0,0.002,628.5,...,97.574,2700.4,NaN,104,12,11,53,1393,41473.4,0
990,1339,0,344,14,3,0,1,0,0.002,520.3,...,95.235,1.3,NaN,205,12,10,63,1344,40916.2,2
991,527,7,40,5,5,2,1,3,0.005,19130.1,...,676.384,1415.5,7.02,101,6,7,95,527,37938.4,6
992,1144,12,120,14,3,0,1,0,0.003,785.2,...,100.805,300.1,NaN,166,12,11,53,1149,33433.5,0
993,1284,0,346,14,0,0,1,0,0.002,466.3,...,94.105,3.3,NaN,289,12,11,134,1289,40927.1,2

In [68]:
temp=[1 if np.isnan(df.iloc[i]['Feature 18']) else 0 for i in range(0,len(df)) ]

In [69]:
len(temp)

994

In [73]:
df['f18_null']=temp # treating null value as a feature ( SINCE IT COUNT IS ALMOST ONE-THIIRD)

In [74]:
df.head()

,Feature 1 (Discrete),Feature 2 (Discrete),Feature 3 (Discrete),Feature 4 (Discrete),Feature 5 (Discrete),Feature 6 (Discrete),Feature 7 (Discrete),Feature 8 (Discrete),Feature 9,Feature 10,...,Feature 15,Feature 18,Feature 19 (Discrete),Feature 20 (Discrete),Feature 21 (Discrete),Feature 22 (Discrete),Feature 23 (Discrete),Feature 24,Target Variable (Discrete),f18_null
0,1404,12,64,14,3,1,1,1,110.502,35775.2,...,5000.5,15.04,104,12,2,32,1409,37677.1,1,0
1,909,0,235,32,1,1,1,1,-40.448,35779.4,...,3720.5,12.03,20,1,0,13,909,25239.1,1,0
2,654,3,175,2,1,1,1,1,-27.445,35770.4,...,4685.4,13.01,1,1,0,13,654,27683.5,1,0
3,1372,12,382,14,2,0,1,0,0.001,509.2,...,NaN,NaN,313,12,10,54,1377,39363.2,0,1
4,786,3,199,2,1,0,1,0,0.001,612.1,...,4.1,NaN,171,1,5,11,786,40044.4,2,1

In [75]:
temp=[1 if np.isnan(df_test.iloc[i]['Feature 18']) else 0 for i in range(0,len(df_test)) ]

In [77]:
len(temp)

426

In [78]:
df_test['f18_null']=temp # Use null values of Feature 18 as a feature

In [79]:
df_test

,Feature 1 (Discrete),Feature 2 (Discrete),Feature 3 (Discrete),Feature 4 (Discrete),Feature 5 (Discrete),Feature 6 (Discrete),Feature 7 (Discrete),Feature 8 (Discrete),Feature 9,Feature 10,...,Feature 14,Feature 15,Feature 18,Feature 19 (Discrete),Feature 20 (Discrete),Feature 21 (Discrete),Feature 22 (Discrete),Feature 23 (Discrete),Feature 24,f18_null
0,146,12,42,14,7,1,1,1,118.004,35693.5,...,1435.935,4200.3,NaN,44,12,2,42,146,37384.5,1
1,35,0,12,5,0,0,1,0,0.001,471.5,...,94.181,531.4,NaN,17,6,8,0,35,41465.1,1
2,1018,8,259,2,1,1,1,1,NaN,35774.5,...,1436.092,5514.2,15.04,1,1,3,20,1018,37826.2,0
3,383,7,117,5,1,1,1,1,53.002,34094.1,...,1440.095,3358.4,15.04,101,6,3,20,383,40277.3,0
4,1216,7,40,5,2,0,1,4,0.005,1471.3,...,115.504,225.1,3.02,276,6,7,43,1221,28419.5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421,51,3,18,2,1,1,1,1,-86.956,35777.2,...,1436.084,2845.5,15.04,20,1,1,22,51,24936.3,0
422,942,35,242,56,1,1,1,1,155.985,35775.1,...,1436.043,2501.5,15.01,12,1,0,12,942,35756.1,0
423,954,3,245,2,1,0,1,3,0.001,788.5,...,100.702,45.2,5.02,12,1,18,103,954,25477.2,0
424,1297,0,355,43,1,1,1,1,50.005,35776.5,...,1436.085,4869.1,15.01,273,15,3,5,1302,39522.2,0
425,1334,3,370,2,1,0,20,0,0.004,612.4,...,96.964,2800.1,44116.02,202,1,4,10,1339,40115.4,0

In [80]:
df['Feature 18']=df['Feature 18'].fillna(df['Feature 18'].mean())

In [82]:
df_test['Feature 18']=df_test['Feature 18'].fillna(df_test['Feature 18'].mean())

In [83]:
df.isna().sum()

Feature 1 (Discrete)           0
Feature 2 (Discrete)           0
Feature 3 (Discrete)           0
Feature 4 (Discrete)           0
Feature 5 (Discrete)           0
Feature 6 (Discrete)           0
Feature 7 (Discrete)           0
Feature 8 (Discrete)           0
Feature 9                     14
Feature 10                     1
Feature 11                     1
Feature 12                     1
Feature 13                     1
Feature 14                     1
Feature 15                    72
Feature 18                     0
Feature 19 (Discrete)          0
Feature 20 (Discrete)          0
Feature 21 (Discrete)          0
Feature 22 (Discrete)          0
Feature 23 (Discrete)          0
Feature 24                     1
Target Variable (Discrete)     0
f18_null                       0
dtype: int64

In [84]:
df['Feature 15']=df['Feature 15'].fillna(df['Feature 15'].mean())

In [85]:
df_test['Feature 15']=df_test['Feature 15'].fillna(df_test['Feature 15'].mean())

In [86]:
df

,Feature 1 (Discrete),Feature 2 (Discrete),Feature 3 (Discrete),Feature 4 (Discrete),Feature 5 (Discrete),Feature 6 (Discrete),Feature 7 (Discrete),Feature 8 (Discrete),Feature 9,Feature 10,...,Feature 15,Feature 18,Feature 19 (Discrete),Feature 20 (Discrete),Feature 21 (Discrete),Feature 22 (Discrete),Feature 23 (Discrete),Feature 24,Target Variable (Discrete),f18_null
0,1404,12,64,14,3,1,1,1,110.502,35775.2,...,5000.500000,15.040000,104,12,2,32,1409,37677.1,1,0
1,909,0,235,32,1,1,1,1,-40.448,35779.4,...,3720.500000,12.030000,20,1,0,13,909,25239.1,1,0
2,654,3,175,2,1,1,1,1,-27.445,35770.4,...,4685.400000,13.010000,1,1,0,13,654,27683.5,1,0
3,1372,12,382,14,2,0,1,0,0.001,509.2,...,2042.519523,2061.806852,313,12,10,54,1377,39363.2,0,1
4,786,3,199,2,1,0,1,0,0.001,612.1,...,4.100000,2061.806852,171,1,5,11,786,40044.4,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
989,1388,0,382,14,2,0,1,0,0.002,628.5,...,2700.400000,2061.806852,104,12,11,53,1393,41473.4,0,1
990,1339,0,344,14,3,0,1,0,0.002,520.3,...,1.300000,2061.806852,205,12,10,63,1344,40916.2,2,1
991,527,7,40,5,5,2,1,3,0.005,19130.1,...,1415.500000,7.020000,101,6,7,95,527,37938.4,6,0
992,1144,12,120,14,3,0,1,0,0.003,785.2,...,300.100000,2061.806852,166,12,11,53,1149,33433.5,0,1
993,1284,0,346,14,0,0,1,0,0.002,466.3,...,3.300000,2061.806852,289,12,11,134,1289,40927.1,2,1

In [87]:
df.isna().sum()

Feature 1 (Discrete)           0
Feature 2 (Discrete)           0
Feature 3 (Discrete)           0
Feature 4 (Discrete)           0
Feature 5 (Discrete)           0
Feature 6 (Discrete)           0
Feature 7 (Discrete)           0
Feature 8 (Discrete)           0
Feature 9                     14
Feature 10                     1
Feature 11                     1
Feature 12                     1
Feature 13                     1
Feature 14                     1
Feature 15                     0
Feature 18                     0
Feature 19 (Discrete)          0
Feature 20 (Discrete)          0
Feature 21 (Discrete)          0
Feature 22 (Discrete)          0
Feature 23 (Discrete)          0
Feature 24                     1
Target Variable (Discrete)     0
f18_null                       0
dtype: int64

In [88]:
df['Feature 9']=df['Feature 9'].fillna(df['Feature 9'].mean())
df_test['Feature 9']=df_test['Feature 9'].fillna(df_test['Feature 9'].mean())

In [91]:
df.isna().sum()

Feature 1 (Discrete)          0
Feature 2 (Discrete)          0
Feature 3 (Discrete)          0
Feature 4 (Discrete)          0
Feature 5 (Discrete)          0
Feature 6 (Discrete)          0
Feature 7 (Discrete)          0
Feature 8 (Discrete)          0
Feature 9                     0
Feature 10                    1
Feature 11                    1
Feature 12                    1
Feature 13                    1
Feature 14                    1
Feature 15                    0
Feature 18                    0
Feature 19 (Discrete)         0
Feature 20 (Discrete)         0
Feature 21 (Discrete)         0
Feature 22 (Discrete)         0
Feature 23 (Discrete)         0
Feature 24                    1
Target Variable (Discrete)    0
f18_null                      0
dtype: int64

In [98]:
df=df.dropna()

In [99]:
df

,Feature 1 (Discrete),Feature 2 (Discrete),Feature 3 (Discrete),Feature 4 (Discrete),Feature 5 (Discrete),Feature 6 (Discrete),Feature 7 (Discrete),Feature 8 (Discrete),Feature 9,Feature 10,...,Feature 15,Feature 18,Feature 19 (Discrete),Feature 20 (Discrete),Feature 21 (Discrete),Feature 22 (Discrete),Feature 23 (Discrete),Feature 24,Target Variable (Discrete),f18_null
0,1404,12,64,14,3,1,1,1,110.502,35775.2,...,5000.500000,15.040000,104,12,2,32,1409,37677.1,1,0
1,909,0,235,32,1,1,1,1,-40.448,35779.4,...,3720.500000,12.030000,20,1,0,13,909,25239.1,1,0
2,654,3,175,2,1,1,1,1,-27.445,35770.4,...,4685.400000,13.010000,1,1,0,13,654,27683.5,1,0
3,1372,12,382,14,2,0,1,0,0.001,509.2,...,2042.519523,2061.806852,313,12,10,54,1377,39363.2,0,1
4,786,3,199,2,1,0,1,0,0.001,612.1,...,4.100000,2061.806852,171,1,5,11,786,40044.4,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
989,1388,0,382,14,2,0,1,0,0.002,628.5,...,2700.400000,2061.806852,104,12,11,53,1393,41473.4,0,1
990,1339,0,344,14,3,0,1,0,0.002,520.3,...,1.300000,2061.806852,205,12,10,63,1344,40916.2,2,1
991,527,7,40,5,5,2,1,3,0.005,19130.1,...,1415.500000,7.020000,101,6,7,95,527,37938.4,6,0
992,1144,12,120,14,3,0,1,0,0.003,785.2,...,300.100000,2061.806852,166,12,11,53,1149,33433.5,0,1
993,1284,0,346,14,0,0,1,0,0.002,466.3,...,3.300000,2061.806852,289,12,11,134,1289,40927.1,2,1

In [100]:

df_test=df_test.dropna()

In [104]:
df.columns

Index(['Feature 1 (Discrete)', 'Feature 2 (Discrete)', 'Feature 3 (Discrete)',
       'Feature 4 (Discrete)', 'Feature 5 (Discrete)', 'Feature 6 (Discrete)',
       'Feature 7 (Discrete)', 'Feature 8 (Discrete)', 'Feature 9',
       'Feature 10', 'Feature 11', 'Feature 12', 'Feature 13', 'Feature 14',
       'Feature 15', 'Feature 18', 'Feature 19 (Discrete)',
       'Feature 20 (Discrete)', 'Feature 21 (Discrete)',
       'Feature 22 (Discrete)', 'Feature 23 (Discrete)', 'Feature 24',
       'Target Variable (Discrete)', 'f18_null'],
      dtype='object')

In [103]:
df_test

,Feature 1 (Discrete),Feature 2 (Discrete),Feature 3 (Discrete),Feature 4 (Discrete),Feature 5 (Discrete),Feature 6 (Discrete),Feature 7 (Discrete),Feature 8 (Discrete),Feature 9,Feature 10,...,Feature 14,Feature 15,Feature 18,Feature 19 (Discrete),Feature 20 (Discrete),Feature 21 (Discrete),Feature 22 (Discrete),Feature 23 (Discrete),Feature 24,f18_null
0,146,12,42,14,7,1,1,1,118.004000,35693.5,...,1435.935,4200.3,1560.762917,44,12,2,42,146,37384.5,1
1,35,0,12,5,0,0,1,0,0.001000,471.5,...,94.181,531.4,1560.762917,17,6,8,0,35,41465.1,1
2,1018,8,259,2,1,1,1,1,5.037701,35774.5,...,1436.092,5514.2,15.040000,1,1,3,20,1018,37826.2,0
3,383,7,117,5,1,1,1,1,53.002000,34094.1,...,1440.095,3358.4,15.040000,101,6,3,20,383,40277.3,0
4,1216,7,40,5,2,0,1,4,0.005000,1471.3,...,115.504,225.1,3.020000,276,6,7,43,1221,28419.5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421,51,3,18,2,1,1,1,1,-86.956000,35777.2,...,1436.084,2845.5,15.040000,20,1,1,22,51,24936.3,0
422,942,35,242,56,1,1,1,1,155.985000,35775.1,...,1436.043,2501.5,15.010000,12,1,0,12,942,35756.1,0
423,954,3,245,2,1,0,1,3,0.001000,788.5,...,100.702,45.2,5.020000,12,1,18,103,954,25477.2,0
424,1297,0,355,43,1,1,1,1,50.005000,35776.5,...,1436.085,4869.1,15.010000,273,15,3,5,1302,39522.2,0
425,1334,3,370,2,1,0,20,0,0.004000,612.4,...,96.964,2800.1,44116.020000,202,1,4,10,1339,40115.4,0

In [116]:
X=df.drop('Target Variable (Discrete)',axis=1)

In [117]:
y=df['Target Variable (Discrete)']

In [108]:
y

0      1
1      1
2      1
3      0
4      2
      ..
989    0
990    2
991    6
992    0
993    2
Name: Target Variable (Discrete), Length: 993, dtype: int64

In [109]:
# Using random forest ( since it is a ensemble technique and use decision tree , therefore no scaling is required)

In [110]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

In [112]:
df.corr() #feature 6 has highest correlation (0.26)

,Feature 1 (Discrete),Feature 2 (Discrete),Feature 3 (Discrete),Feature 4 (Discrete),Feature 5 (Discrete),Feature 6 (Discrete),Feature 7 (Discrete),Feature 8 (Discrete),Feature 9,Feature 10,...,Feature 15,Feature 18,Feature 19 (Discrete),Feature 20 (Discrete),Feature 21 (Discrete),Feature 22 (Discrete),Feature 23 (Discrete),Feature 24,Target Variable (Discrete),f18_null
Feature 1 (Discrete),1.000000,0.104168,0.754656,0.203431,0.012454,-0.054685,0.010039,0.012528,0.011120,-0.162555,...,0.015511,3.889789e-02,0.455949,0.114108,0.135273,0.176157,0.999994,0.049936,-0.037171,1.965014e-01
Feature 2 (Discrete),0.104168,1.000000,0.051238,0.402032,0.060258,0.041697,0.056351,-0.165951,0.122037,0.116528,...,0.054070,2.278943e-02,0.058057,0.252122,-0.065370,0.007977,0.103969,-0.148014,-0.049700,-6.928630e-02
Feature 3 (Discrete),0.754656,0.051238,1.000000,0.219418,0.002180,-0.069266,0.020389,-0.064673,0.023182,-0.150814,...,-0.049940,3.339094e-02,0.355720,0.070865,0.093952,0.103611,0.754746,0.048968,-0.073013,2.237192e-01
Feature 4 (Discrete),0.203431,0.402032,0.219418,1.000000,-0.053942,-0.017015,0.005777,-0.257463,0.151438,0.033234,...,-0.020784,-1.031873e-02,0.108929,0.424353,-0.072589,0.012039,0.203439,0.056348,-0.015992,4.313588e-02
Feature 5 (Discrete),0.012454,0.060258,0.002180,-0.053942,1.000000,-0.019176,0.053153,0.245099,0.022894,-0.158284,...,-0.101938,4.865216e-03,0.134287,-0.035612,-0.045703,0.225760,0.011844,-0.201791,0.172235,-2.217580e-01
Feature 6 (Discrete),-0.054685,0.041697,-0.069266,-0.017015,-0.019176,1.000000,-0.093668,0.152704,0.063677,0.601260,...,0.331662,-4.060993e-02,-0.329739,-0.102280,-0.426126,-0.117607,-0.054626,-0.121379,0.262826,-2.639969e-01
Feature 7 (Discrete),0.010039,0.056351,0.020389,0.005777,0.053153,-0.093668,1.000000,-0.055176,-0.057440,-0.190587,...,-0.069993,9.931442e-02,0.102931,0.048143,0.048969,0.068503,0.009901,0.042830,-0.171150,1.024229e-01
Feature 8 (Discrete),0.012528,-0.165951,-0.064673,-0.257463,0.245099,0.152704,-0.055176,1.000000,-0.046928,-0.227661,...,-0.082764,8.674369e-02,0.022030,-0.153121,0.010647,0.158870,0.011733,-0.162042,0.078064,-1.574372e-01
Feature 9,0.011120,0.122037,0.023182,0.151438,0.022894,0.063677,-0.057440,-0.046928,1.000000,0.144369,...,0.020181,-1.153099e-02,-0.015835,0.061929,-0.075075,-0.042626,0.010976,0.051416,0.060760,1.052350e-02
Feature 10,-0.162555,0.116528,-0.150814,0.033234,-0.158284,0.601260,-0.190587,-0.227661,0.144369,1.000000,...,0.585145,-9.253467e-02,-0.470362,-0.166635,-0.468624,-0.252332,-0.162063,-0.200572,0.024457,-3.565173e-01
Feature 11,-0.102197,0.104396,-0.083958,0.023875,-0.119851,0.773870,-0.146982,-0.050091,0.117152,0.827929,...,0.516889,-4.017060e-02,-0.374166,-0.100182,-0.450350,-0.224672,-0.101763,-0.212668,0.084739,-3.331650e-01
Feature 12,0.093201,-0.027089,0.090098,-0.036212,0.015438,0.512958,0.108969,0.301108,-0.018248,-0.109918,...,0.004901,9.184266e-02,0.061911,0.014755,-0.084593,-0.038763,0.093324,-0.033226,0.079235,7.634224e-03
Feature 13,0.118206,-0.050795,0.064418,0.003601,0.244901,-0.565357,0.164921,0.055686,-0.120633,-0.859556,...,-0.509687,8.815750e-02,0.463050,0.222816,0.412296,0.216307,0.117841,0.198579,0.054799,2.909500e-01
Feature 14,-0.130564,0.123533,-0.112438,0.040969,-0.145475,0.691943,-0.206350,-0.134380,0.134743,0.916310,...,0.564456,-7.392891e-02,-0.417465,-0.116167,-0.456255,-0.239837,-0.130106,-0.224151,0.050529,-3.585059e-01
Feature 15,0.015511,0.054070,-0.049940,-0.020784,-0.101938,0.331662,-0.069993,-0.082764,0.020181,0.585145,...,1.000000,-3.698203e-02,-0.329753,-0.182511,-0.295545,-0.185332,0.015886,-0.108623,-0.117802,-2.237336e-01
Feature 18,0.038898,0.022789,0.033391,-0.010319,0.004865,-0.040610,0.099314,0.086744,-0.011531,-0.092535,...,-0.036982,1.000000e+00,0.097650,0.038001,0.060442,0.079935,0.038775,0.064681,-0.062427,1.281260e-15
Feature 19 (Discrete),0.455949,0.058057,0.355720,0.108929,0.134287,-0.329739,0.102931,0.022030,-0.015835,-0.470362,...,-0.329753,9.765040e-02,1.000000,0.352632,0.266288,0.156484,0.455761,0.187869,0.047278,3.288902e-01
Feature 20 (Discrete),0.114108,0.252122,0.070865,0.424353,-0.035612,-0.102280,0.048143,-0.153121,0.061929,-0.166635,...,-0.182511,3.800108e-02,0.352632,1.000000,0.068637,0.048424,0.113911,0.113478,0.124866,8.882215e-02
Feature 21 (Discrete),0.135273,-0.065370,0.093952,-0.072589,-0.045703,-0.426126,0.048969,0.010647,-0.075075,-0.468624,...,-0.295545,6.044230e-02,0.266288,0.068637,1.000000,0.338511,0.135156,0.133742,-0.068477,2.495658e-01
Feature 22 (Discrete),0.176157,0.007977,0.103611,0.012039,0.225760,-0.117607,0.068503,0.158870,-0.042626,-0.252332,...,-0.185332,7.993462e-02,0.156484,0.048424,0.338511,1.000000,0.175751,-0.132890,0.040423,1.493184e-03
Feature 23 (Discrete),0.999994,0.103969,0.754746,0.203439,0.011844,-0.054626,0.009901,0.011733,0.010976,-0.162063,...,0.015886,3.877483e-02,0.455761,0.113911,0.135156,0.175751,1.000000,0.050271,-0.037498,1.971385e-01
Feature 24,0.049936,-0.148014,0.048968,0.056348,-0.201791,-0.121379,0.042830,-0.162042,0.051416,-0.200572,...,-0.108623,6.468114e-02,0.187869,0.113478,0.133742,-0.132890,0.050271,1.000000,0.088112,3.865177e-01
Target Variable (Discrete),-0.037171,-0.049700,-0.073013,-0.015992,0.172235,0.262826,-0.171150,0.078064,0.060760,0.024457,...,-0.117802,-6.242722e-02,0.047278,0.124866,-0.068477,0.040423,-0.037498,0.088112,1.000000,-7.534921e-02
f18_null,0.196501,-0.069286,0.223719,0.043136,-0.221758,-0.263997,0.102423,-0.157437,0.010523,-0.356517,...,-0.223734,1.281260e-15,0.328890,0.088822,0.249566,0.001493,0.197139,0.386518,-0.075349,1.000000e+00

In [113]:
rf=RandomForestClassifier(random_state=0)

In [114]:
from sklearn.model_selection import train_test_split

In [118]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [119]:
X_train

,Feature 1 (Discrete),Feature 2 (Discrete),Feature 3 (Discrete),Feature 4 (Discrete),Feature 5 (Discrete),Feature 6 (Discrete),Feature 7 (Discrete),Feature 8 (Discrete),Feature 9,Feature 10,...,Feature 14,Feature 15,Feature 18,Feature 19 (Discrete),Feature 20 (Discrete),Feature 21 (Discrete),Feature 22 (Discrete),Feature 23 (Discrete),Feature 24,f18_null
549,1400,12,385,14,0,0,1,0,0.004,619.1,...,97.405,4.1,2061.806852,317,12,11,53,1405,37166.4,1
1,909,0,235,32,1,1,1,1,-40.448,35779.4,...,1436.111,3720.5,12.030000,20,1,0,13,909,25239.1,0
38,636,0,175,2,1,1,1,1,328.502,35778.2,...,1436.103,4100.1,16.030000,1,1,0,19,636,33153.2,0
482,130,12,42,14,7,2,1,3,0.005,21452.4,...,773.213,2200.4,8.020000,44,12,2,32,130,38251.5,0
914,185,12,65,14,3,0,1,0,0.005,729.2,...,99.603,100.5,2061.806852,58,12,10,32,185,28058.2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
835,376,0,116,5,1,1,1,1,36.002,35792.5,...,1436.104,2700.5,15.010000,38,7,3,20,376,41191.1,0
192,949,3,245,2,1,0,1,3,0.001,789.1,...,100.704,45.2,5.020000,12,1,18,103,949,25417.5,0
629,1011,0,233,2,2,0,1,3,0.005,494.1,...,97.661,1.2,2061.806852,224,1,1,10,1011,40976.4,1
559,457,3,145,2,1,0,1,3,0.005,1407.3,...,114.003,450.1,10.040000,1,1,1,61,457,25163.2,0
684,382,7,117,5,1,1,1,1,140.001,35420.2,...,1430.605,3400.5,15.010000,100,6,3,20,382,39487.5,0

In [120]:
X_test

,Feature 1 (Discrete),Feature 2 (Discrete),Feature 3 (Discrete),Feature 4 (Discrete),Feature 5 (Discrete),Feature 6 (Discrete),Feature 7 (Discrete),Feature 8 (Discrete),Feature 9,Feature 10,...,Feature 14,Feature 15,Feature 18,Feature 19 (Discrete),Feature 20 (Discrete),Feature 21 (Discrete),Feature 22 (Discrete),Feature 23 (Discrete),Feature 24,f18_null
820,350,4,112,1,1,1,1,1,25.505,35780.5,...,1436.041,3170.3,12.040000,22,2,1,80,350,27554.3,0
722,837,0,180,2,3,3,1,1,0.001,1375.3,...,1433.001,1360.3,3.010000,122,1,1,10,837,40482.1,0
31,34,7,11,5,0,0,1,3,0.003,558.1,...,96.063,53.5,3.050000,16,6,3,0,34,39133.3,0
548,497,4,145,2,1,0,1,3,0.004,1413.2,...,114.103,700.5,15.030000,30,14,3,94,497,38043.2,0
968,1078,38,274,66,1,0,1,0,0.003,696.3,...,99.603,12.4,2061.806852,245,55,3,30,1078,28370.1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
612,753,20,58,18,3,1,8,1,74.072,35783.5,...,1436.083,1060.1,43958.040000,145,18,6,117,753,27525.5,0
601,641,0,175,2,1,1,1,1,304.501,35777.3,...,1436.105,3300.2,15.010000,1,1,0,12,641,40874.5,0
665,1406,12,382,14,2,1,1,1,129.845,35778.3,...,1436.135,5200.1,2061.806852,104,12,2,32,1411,37804.4,1
978,356,4,112,1,1,1,1,1,48.005,35777.4,...,1436.124,5102.3,15.010000,30,14,0,19,356,38992.2,0
632,316,3,99,2,1,1,1,1,-61.499,35776.1,...,1436.064,6658.2,15.050000,1,1,3,20,316,39008.1,0

In [123]:
param_grid= { 'max_features':['auto','log2','sqrt'] , 'max_depth':[3,4,5,6,7] }

In [124]:
model_temp=GridSearchCV(estimator=rf,param_grid=param_grid,cv=5)

In [127]:
model_temp.fit(X_train,y_train)

C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Charanpreet Singh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators='warn', n_jobs=None,
                                              oob_score=False, random_state=0,
                                              verbose=0, warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'max_depth': [3, 4, 5, 6, 7],
                         'max_features': ['auto', 'log2', 'sqrt']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [128]:
model_temp.best_params_

{'max_depth': 7, 'max_features': 'auto'}

In [129]:
pred=model_temp.predict(X_test)

In [130]:
pred

array([1, 5, 2, 1, 2, 0, 1, 1, 2, 6, 6, 0, 0, 1, 1, 0, 2, 2, 1, 0, 6, 0,
       1, 1, 0, 1, 1, 1, 6, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 6, 1,
       1, 1, 0, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 0, 2, 6, 2, 1, 2, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 5, 5, 1, 0, 1, 0, 6, 1, 2, 1, 1, 0, 0, 0,
       5, 1, 1, 1, 6, 1, 2, 0, 1, 0, 1, 1, 2, 5, 6, 1, 0, 1, 2, 1, 2, 0,
       1, 1, 6, 1, 0, 1, 0, 1, 1, 2, 6, 1, 1, 0, 1, 1, 0, 6, 1, 0, 1, 0,
       1, 0, 1, 0, 2, 1, 6, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 2, 1, 0, 1,
       2, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 6, 2, 1, 1, 1, 1, 0, 1,
       1, 2, 0, 0, 1, 0, 0, 6, 0, 1, 0, 1, 1, 1, 1, 2, 1, 1, 0, 0, 1, 2,
       1, 1, 1, 0, 1, 2, 0, 1, 0, 0, 6, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 2,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 6, 2, 1, 1, 2, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [131]:
from sklearn.metrics import accuracy_score

In [132]:
fa=accuracy_score(y_test,pred)

In [133]:
fa

0.8795180722891566

In [134]:
# Accuracy using Randomforest classifier comes out to be 88 %

In [135]:
output=model_temp.predict(df_test)

In [136]:
output # this is output for test.csv

array([ 1,  0,  1,  1,  1,  2,  1,  5,  1,  0,  1,  6,  0,  1,  2,  0,  1,
        1,  1,  1,  5,  0,  1,  0,  0,  2,  6,  0,  1,  0,  1,  1,  6,  1,
        0,  6,  0,  0,  2,  1,  1,  1,  1,  0,  2,  1,  0,  6,  1,  1,  1,
        1,  1,  1,  1,  6,  2,  0,  0,  1,  1,  1,  6,  1,  1,  2,  2,  1,
        2,  1,  2,  1,  1,  6,  1,  1,  1,  1,  1,  5,  1,  0,  2,  6,  0,
        1,  1,  1,  1,  1,  0,  2,  1,  1,  1,  0,  1,  2,  0,  1,  0,  0,
        1,  1,  1,  1,  2,  0,  2,  1,  0,  1,  0,  0,  6,  0,  1,  2,  1,
        0,  1,  1,  1,  6,  1,  1,  1,  1,  1,  1,  1,  1,  0,  0,  2,  8,
        2,  1,  0,  0,  1,  0,  0,  1,  1,  6,  2,  2,  0,  1,  1,  6,  1,
        1,  1,  1,  0,  1,  1,  0,  1,  0,  0,  0,  1,  0,  0,  0,  1,  0,
        0,  1,  1,  1,  1,  1,  1,  0,  2,  1,  1,  1,  2,  1,  1,  5,  2,
        1,  5,  0,  1,  6,  1,  1,  0,  1,  1,  1,  1,  0,  1,  6,  1,  1,
        1,  0,  1,  1,  0,  0,  0,  0,  2,  1,  1,  0,  1,  1,  1,  1,  0,
        1,  1,  6,  1,  1,  0,  1,  2,  1,  1,  1,  1,  0,  1,  1,  0,  0,
        0,  1,  1,  2,  1,  5,  1,  6,  0,  1,  0,  5,  1,  1,  1,  2,  0,
        0,  0,  1,  6,  1,  1,  0,  0,  0,  1,  0,  0,  1,  0,  0,  1,  2,
        5,  6,  0,  0,  2,  1,  1,  1,  1,  5,  5,  1,  2,  1,  0,  1,  0,
        1,  1,  6,  0,  5,  0,  1, 14,  0,  1,  1,  1,  1,  5,  1,  1,  1,
        6,  1,  2,  1,  1,  1,  1,  1,  2,  1,  2,  1,  1,  1,  0,  0,  1,
        0,  1,  0,  1,  1,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  0,  1,
        1,  1,  0,  2,  0,  0,  1,  1,  1,  1,  2,  1,  1,  2,  0,  6,  2,
        6,  2,  1,  2,  0,  1,  0,  1,  0,  1,  0,  1,  1,  1,  1,  0,  1,
        1,  1,  0,  1,  2,  1,  2,  1,  1,  0,  2,  1,  1,  1,  1,  0,  0,
        1,  1,  1,  5,  1,  2,  2,  1,  1,  6,  2,  1,  0,  1,  1,  1,  0,
        1,  1,  2,  1,  1,  1,  0,  2,  0,  1,  0,  1,  1,  1,  1,  0],
      dtype=int64)